version: '3.7'

services:
  bcexerciseapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: bcexerciseapi
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run start:watch
